name: Analyse SAST avec Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit analysis
        run: bandit -r . --format plain | grep "Severity: High"
